USE [master]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[InventV2]') AND type in (N'U'))
DROP DATABASE [InventV2]
GO

CREATE DATABASE [InventV2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventV2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\InventV.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InventV2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\InventV_log.ldf' , SIZE = 335872KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventV2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventV2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventV2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventV2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventV2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventV2] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventV2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventV2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventV2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventV2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventV2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventV2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventV2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventV2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventV2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventV2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventV2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventV2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventV2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventV2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventV2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventV2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventV2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventV2] SET RECOVERY FULL 
GO

ALTER DATABASE [InventV2] SET  MULTI_USER 
GO

ALTER DATABASE [InventV2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventV2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventV2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventV2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InventV2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InventV2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InventV2] SET  READ_WRITE 
GO

ALTER DATABASE [InventV2]   Collate sql_latin1_general_cp1_cs_as 
GO


